TwoCircle-Team5/TwoCircle

index.html
=> conf: add index.html

index.html, package-lock.json, package.json, scss/abstracts/_variable.scss, scss/base/_preset.scss, scss/style.scss
=> conf: Configure scss setting

.gitignore, scss/abstracts/_variable.scss, scss/base/_preset.scss
=> conf: Configure setting

.gitignore, index.html, package-lock.json, package.json, pages/login.html, pages/payment.html, pages/product_details.html, pages/product_list.html, pages/purchase_history.html, pages/signup.html, scss/login.scss, scss/product_list.scss, scss/signup.scss
.gitignore 내용변경
class name 변경
파일 경로 수정
parcel 2버전 -> 1버전으로 교체
package json 업로드
=> .gitignore 내용변경, Class name 변경, 이미지 또는 파일의 경로 수정, package파일 업로드

package-lock.json, package.json, pages/order_completed.html, pages/product_details.html, source/api/account/product_details_api.js, source/api/certified/authcheck_api.js, source/api/certified/login_api.js, source/api/certified/logout_api.js, source/api/certified/signup_api.js, source/api/certified/userupdate_api.js, source/api/requests.js, source/js/login.js, source/js/product_details.js, source/js/route.js, source/js/signup.js
- request.js: url, headers 정보
- login, logout, signup, authcheck, userupdate: api 기본 기능 추가
- 제품상세, 결제, 구매, 라우터 초기 파일 추가
- package-lock.json
- package.json: parcel, navigo 추가
=> api, js, 주문완료 페이지, .json추가

package.json
package.json 에 있는 dev와 build의  파일경로를 수정하였습니다.
=> Docs: Modified Package.json

pages/account.html, scss/account.scss, source/api/account/account_able_check.js, source/api/account/account_add.js, source/api/account/account_add_check.js, source/api/account/account_delete.js, source/js/account.js
- api 파일과 account.js 파일 코드 정리 
- 선택 가능한 계좌 구현 
- html script tag 추가 
- 전화번호 정규식 구현
=> 계좌관리  api 분리 및 선택 가능한 계좌 조회 구현

pages/admin/product_list.html, source/js/admin/product_add.js, source/js/admin/product_list.js
- 제품삭제
- 전체삭제
- 선택삭제
- 리스트에 제품추가 링크 연결
=> feat: list check delete

pages/user/purchase_history.html, scss/user/purchase_history.scss, source/api/products/user/purchase_cancel_api.js, source/api/products/user/purchase_history_api.js, source/api/products/user/purchase_ok_api.js, source/js/purchase_history.js
왼쪽 상단 1개월, 3개월, 6개월, 1년 버튼으로 필터 구현
=> Date Filter 구현

pages/user/payment.js, pages/user/product_details.js
제품상세페이지: 구매, 장바구니버튼에 대한 데이터를 세분화 시켜 넣음
결제 페이지: 로컬스토리지에 있는 데이터 걸제페이지에 리스트형태로 보이게 작성
=> 장바구니, 구매 버튼에 대한 코드 변경, 주문정보 리스트 페이지에 띄우기

pages/user/cart.html, pages/user/mypage.html, pages/user/product_list.html, pages/user/user_information.html, pages/user/wish_list.html, scss/base/_preset.scss, scss/user/cart.scss, scss/user/my_page.scss, scss/user/wish_list.scss, source/js/cart.js, source/js/product_list.js, source/js/wish_list.js
- 장바구니 로컬스토리지 저장된 값 불러와 리스트에 넣어주기 
- 장바구니 수량 버튼 클릭 시 수량 및 가격 증감 구현 
- 장바구니 구매 시 변경된 값 및 해당 부분 로컬스토리지에 저장  구현
- 상품 리스트 하트 누를 시 찜 리스트 구현을 위한 로컬스토리지 저장 구현  
- 상품 리스트 하트 다시 누르면 해당 리스트 로컬스토리지에서 제거 및 하트 변경 
- 찜 리스트 로컬스토리지 저장된 값 불러와 리스트에 넣어주기 
- 찜 하트 풀 시 찜 리스트에서 사라지게 하기
- 마이 페이지 구조 무너짐 현상 고침 
- 찜 리스트 구조 및 레이아웃 스타일 변경
=> 로컬스토리지 이용한 찜리스트 및 장바구니 구현 

source/js/login.js
잘못된 코드가 섞여있어서 로그인이 안되는 현상을 수정했습니다.`
=> fix: Delete Wrong Code

source/js/product_list.js
=> 충돌시 오류부분 수정 

.gitignore, index.html, pages/user/product_details.js, source/js/product_details.js
=> 카카오톡 공유 기능 추가

pages/user/login.js, pages/user/signup.js, scss/user/login.scss, scss/user/signup.scss, source/api/certified/signup_api.js, source/route.js
- 전체적인 너비 수정
- 이미지 업로드 디자인
- 로그인 전에 구매 시도 시 로그인 화면으로 이동하도록 가드
=> 로그인,회원가입 및 구매페이지 가드 

source/js/user_info.js
feat: 이름변경 시 유효한 이름인지 검사하는 기능 추가
=> feat: 이름변경 시 유효한 이름인지 검사하는 기능 추가

pages/user/purchase_history.js, scss/user/purchase_history.scss, source/js/purchase_history.js
=> feat: 구매내역이 없을 때 문구 추가

scss/user/purchase_history.scss, source/js/purchase_history.js
=> 구매내역 페이지 수정

index.html, pages/admin/product_add.js, pages/admin_wrap.js, scss/admin/admin_product_list.scss, scss/admin/product.scss, scss/admin/product_add.scss, scss/base/_preset.scss, source/js/admin/product.js, source/js/admin/product_add.js, source/js/admin/product_list.js, source/route.js
- swiper 버전 변경 (에러 수정되는듯 보였으나... swiper의 자체 문제로 보임)
- login 값 없을때 error 나는 부분 수정
- 어드민 dashboard에 사이드바 추가
- product_list 삭제 기능 에러 수정
- 판매중 매진 글자색 추가
- prdouct add main tag 기능 추가
- 상세페이지 main tag 분리
=> 에러 수정 및 어드민 기능 수정

pages/header.js, scss/user/product_details.scss
=> Fix: 다크모드 오류 업데이트!
